FROM friendica

# Environment variables
ENV MYSQL_HOST=db
ENV MYSQL_USER=friendica
ENV MYSQL_PASSWORD=my-secret_pw
ENV MYSQL_DATABASE=friendica
ENV FRIENDICA_ADMIN_MAIL=root@friendica.local

ENV REDIS_HOST=friendica-redis
ENV REDIS_PORT=6379
ENV REDIS_PW=redispass